version: "3.3"

services:
  app-staking:
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    env_file:
      - .env